apiVersion: v1
kind: Template
metadata:
  name: certbot-requirements
  annotations:
    description: "Certbot Requirements"
    iconClass: "file-certificate"
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: certbot-admin
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: certbot
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: certbot
- apiVersion: v1
  kind: Secret
  metadata:
    name: cloudflare-credentials
  stringData:
    cloudflare.ini: |
      dns_cloudflare_email = ${CLOUDFLARE_EMAIL}
      dns_cloudflare_api_key = ${CLOUDFLARE_API_KEY}
  type: Opaque
parameters:
- name: CLOUDFLARE_API_KEY
  requried: true
- name: CLOUDFLARE_EMAIL
  required: true
